stages:
    - build

build_intel:
    stage: build
    script:
        - source /home/ci_software/intel-19.1.sh
        - rm -fr external/libint2
        - ln -s /sw/libint/2/5/0/intel/19/1 external/libint2
        - mkdir build
        - cd build
        - cmake -DCMAKE_CXX_FLAGS='-O3' -DCMAKE_C_FLAGS='-O3' -DCMAKE_Fortran_FLAGS='-O3' ..
        - make -j8
        - ctest

build_gcc:
    stage: build
    script:
        - source /home/ci_software/gcc-8.2.0.sh
        - rm -fr external/libint2
        - ln -s /sw/libint/2/5/0/gcc/8/2/0 external/libint2
        - mkdir build
        - cd build
        - cmake -DCMAKE_CXX_FLAGS='-O3' -DCMAKE_C_FLAGS='-O3' -DCMAKE_Fortran_FLAGS='-O3' ..
        - make -j8
        - ctest


