stages:
    - build

build_intel:
    stage: build
    script:
        - export PATH=/home/software/lua/current/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:$PATH
        - echo $PATH
        - echo $MODULEPATH
        - module spider
        - cat /home/modulefiles/compiler_dep/intel/19.1/hdf5/1.10.5
        - module load eigen
        - module load intel
        - module load hdf5
        - module load cmake
        - rm -fr external/libint2
        - ln -s /sw/libint/2/5/0/intel/19/1 external/libint2
        - mkdir build
        - cd build
        - cmake -DCMAKE_CXX_FLAGS='-O3' -DCMAKE_C_FLAGS='-O3' -DCMAKE_Fortran_FLAGS='-O3' ..
        - make -j8
        - ctest


build_gcc:
    stage: build
    script:
        - export PATH=/home/software/lua/current/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:$PATH
        - echo $PATH
        - echo $MODULEPATH
        - module spider
        - cat /home/modulefiles/compilers/gcc/8.2.0
        - module load eigen
        - module load gcc
        - module load hdf5
        - module load cmake
        - rm -fr external/libint2
        - ln -s /sw/libint/2/5/0/gcc/8/2/0 external/libint2
        - mkdir build
        - cd build
        - cmake -DCMAKE_CXX_FLAGS='-O3' -DCMAKE_C_FLAGS='-O3' -DCMAKE_Fortran_FLAGS='-O3' ..
        - make -j8
        - ctest

