stages:
    - build

build_intel:
    stage: build
    artifacts:
        when: always
        paths:
            - build/Testing/Temporary/LastTest.log
        name: "$CI_JOB_ID-$CI_JOB_NAME"
    script:
        - source /home/ci_software/intel-19.1.sh
        - mkdir build
        - cd build
        - cmake -DLibint2_ROOT=/sw/libint/2/5/0/intel/19/1 =-DCMAKE_CXX_FLAGS='-O3' -DCMAKE_C_FLAGS='-O3' -DCMAKE_Fortran_FLAGS='-O3'  ..
        - make -j5
        - ctest

build_gcc:
    stage: build
    artifacts:
        when: always
        paths:
            - build/Testing/Temporary/LastTest.log
        name: "$CI_JOB_ID-$CI_JOB_NAME"
    script:
        - source /home/ci_software/gcc-8.2.0.sh
        - mkdir build
        - cd build
        - cmake -DLibint2_ROOT=/sw/libint/2/5/0/gcc/8/2/0 -DCMAKE_CXX_FLAGS='-O3' -DCMAKE_C_FLAGS='-O3' -DCMAKE_Fortran_FLAGS='-O3' ..
        - make -j5
        - ctest

build_mpi_gcc:
    stage: build
    artifacts:
        when: always
        paths:
            - build/Testing/Temporary/LastTest.log
        name: "$CI_JOB_ID-$CI_JOB_NAME"
    script:
        - source /home/ci_software/gcc-8.2.0_mpich-3.2.1.sh
        - mkdir build
        - cd build
        - cmake -DLibint2_ROOT=/sw/libint/2/5/0/gcc/8/2/0 -DCMAKE_CXX_FLAGS='-O3' -DCMAKE_C_FLAGS='-O3' -DCMAKE_Fortran_FLAGS='-O3' -DCQ_ENABLE_MPI=ON  -DCQ_SCALAPACK_LIBRARIES="$SCALAPACK_LIBRARY_DIR/libscalapack.a" -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_BUILD_TYPE=Release ..
        - make -j6
        - make test
