name: Docker_testing

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3        
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Get_CQ_Version
        run: export CQ_VERSION=$(grep "project(ChronusQ" -A 7 CMakeLists.txt | grep "VERSION" | sed 's/ \+VERSION //')
      -
        name: Build_docker
        run: docker build -t uwligroup/chronusq:$CQ_VERSION .
      -
        name: Push_image
        run: docker push uwligroup/chronusq:$CQ_VERSION
      -
        name: Update_tag
        run: docker tag uwligroup/chronusq:$CQ_VERSION uwligroup/chronusq:latest
      -
        name: Push_to_tag
        run: docker push uwligroup/chronusq:latest
      -
        name: after_script
        run: docker logout
